<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.2.0" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\FractalPainter\Application\static\index.html">
        <Link>static\index.html</Link>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TagCloud\TagCloud.csproj" />
    </ItemGroup>

</Project>
